### ISSUE TITLE
Plugin availability on RocketModFix

### ISSUE THREAD

**Issue by d3adwolf** [01-Feli/F.RustResources#3]
Should we expect your plugin on RocketMod again, due to the development of [RocketModFix](https://github.com/RocketModFix/RocketModFix)?

**Comment by negrifelipe** [comment]
There is already a rocketmod version that is up to date with the openmod one

**Comment by d3adwolf** [comment]
Saw it in the release, thanks! Didn't initially see the RocketMod branch on the UnturnedStore for download.
